# Add the JWKS endpoint
deployment:
  identity:
    jwksendpoint: 'https://AUTH0_DOMAIN/.well-known/jwks.json'

# Set the policies
access:
  policies:
    - type: Query
      policyDefault:
        condition: true
      rules:
        - condition: '?$jwt' # Require JWT
          fields: [me] # Define fields that require JWT
