import { useEffect, useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useUser } from '@auth0/nextjs-auth0/client';
import styles from '@/styles/Home.module.css';

export default function Home() {
  const { isLoading } = useUser();

  const [userData, setUserData] = useState<null | {
    name: string;
    picture: string;
  }>(null);

  useEffect(() => {
    async function fetchData() {
      const res = await fetch('/api/graphql', {
        method: 'POST',
        body: JSON.stringify({
          query: `
            query {
              me {
                name
                picture
              }
            }
          `,
        }),
      });
      const json = await res.json();

      if (json?.data?.me) setUserData(json.data.me);
    }

    fetchData();
  }, [setUserData]);

  return (
    <>
      <Head>
        <title>My StepZen App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>
          <div>
            <a
              href='https://stepzen.com?utm_source=with-auth0'
              target='_blank'
              rel='noopener noreferrer'
            >
              By{' '}
              <Image
                src='//stepzen.com/images/logo.svg'
                alt='StepZen Logo'
                className={styles.stepzenLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        {isLoading ? (
          <div className={styles.center}>Loading...</div>
        ) : (
          <div className={styles.center}>
            {userData ? (
              <div className={styles.profile}>
                <img
                  src={userData.picture}
                  alt={`${userData.name}'s profile picture`}
                  width={200}
                  height={200}
                />
                <p>
                  <strong>Welcome {userData?.name}!</strong>{' '}
                  <a href='/api/auth/logout'>Logout</a>
                </p>
              </div>
            ) : (
              <Link href='/api/auth/login' className={styles.loginButton}>
                <span className={styles.auth0Logo} />
                Login with Auth0
              </Link>
            )}
          </div>
        )}
      </main>
    </>
  );
}
