import { useEffect, useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import { useUser } from '@auth0/nextjs-auth0/client';
import styles from '@/styles/Home.module.css';
import Link from 'next/link';

export default function Home() {
  const { error, isLoading } = useUser();
  const [userData, setUserData] = useState<null | { name: string }>(null);

  useEffect(() => {
    async function fetchData() {
      const res = await fetch('/api/graphql', {
        method: 'POST',
        body: JSON.stringify({
          query: `
            query {
              me {
                email
              }
            }
          `,
        }),
      });
      const json = await res.json();

      if (json?.data?.me) setUserData(json.data.me);
    }

    fetchData();
  }, [setUserData]);

  if (isLoading) return <div>Loading...</div>;
  if (error) return <div>{error.message}</div>;

  return (
    <>
      <Head>
        <title>My StepZen App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>
          <div>
            <a
              href='https://stepzen.com?utm_source=with-auth0'
              target='_blank'
              rel='noopener noreferrer'
            >
              By{' '}
              <Image
                src='//stepzen.com/images/logo.svg'
                alt='StepZen Logo'
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          {isLoading && <span>Loading...</span>}
          {error && <span>Something went wrong...</span>}

          {userData ? (
            <div>
              Welcome {userData.email}! <a href='/api/auth/logout'>Logout</a>
            </div>
          ) : (
            <Link href='/api/auth/login'>Login</Link>
          )}
        </div>
      </main>
    </>
  );
}
