import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

// This gets called on every request
export async function getServerSideProps() {
  let headers = {};

  headers["Content-Type"] = "application/json";

  var graphql = JSON.stringify({
    query:
      "query spacexdataQuery($id: String){\n    spacexdataQuery(id: $id){\n        auto_update\n        capsules\n        cores{\n            core\n            flight\n            gridfins\n            landing_attempt\n            landing_success\n            landing_type\n            landpad\n            legs\n            reused\n        }\n        crew{\n            crew\n            role\n        }\n        date_local\n        date_precision\n        date_unix\n        date_utc\n        details\n        failures{\n            altitude\n            reason\n            time\n        }\n        fairings{\n            recovered\n            recovery_attempt\n            reused\n            ships\n        }\n        flight_number\n        id\n        launch_library_id\n        launchpad\n        links{\n            article\n            flickr{\n                original\n                small\n            }\n            patch{\n                large\n                small\n            }\n            presskit\n            reddit{\n                campaign\n                launch\n                media\n                recovery\n            }\n            webcast\n            wikipedia\n            youtube_id\n        }\n        name\n        net\n        payloads\n        rocket\n        ships\n        static_fire_date_unix\n        static_fire_date_utc\n        success\n        tbd\n        upcoming\n        window\n    }\n}",
    variables: { id: "5eb87d42ffd86e000604b384" },
  });

  var requestOptions = {
    method: "POST",
    headers: headers,
    body: graphql,
  };

  const res = await fetch(
    "https://public6ff2fe39063e3b4f.stepzen.net/api/spacexdata/__graphql",
    requestOptions
  )
    .then((response) => response.json())
    .then((res) => res)
    .catch((error) => console.log("error", error));
  return { props: { res } };
}

export default function Home({ res }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{res.data.spacexdataQuery[0].id}</h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
